### ISSUE TITLE
npm i  npm run dev 运行不起来，win7系统

### ISSUE THREAD

**Issue by suntsh** [57code/vite2-in-action#5]
D:\projects\vite2-in-action>node -v
v12.20.2

D:\projects\vite2-in-action>npm run dev

> vite2-in-action@0.0.0 dev
> cross-env NODE_ENV=development vite

failed to load config from D:\projects\vite2-in-action\vite.config.js
error when starting dev server:
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Object.writeToStdin (D:\projects\vite2-in-action\node_modules\esbuild\lib
\main.js:1413:19)
    at sendRequest (D:\projects\vite2-in-action\node_modules\esbuild\lib\main.js
:576:14)
    at Object.buildOrServe (D:\projects\vite2-in-action\node_modules\esbuild\lib
\main.js:1044:11)
    at D:\projects\vite2-in-action\node_modules\esbuild\lib\main.js:1444:17
    at new Promise (<anonymous>)
    at Object.build (D:\projects\vite2-in-action\node_modules\esbuild\lib\main.j
s:1443:14)
    at Object.build (D:\projects\vite2-in-action\node_modules\esbuild\lib\main.j
s:1334:51)

**Comment by jaysonwu991** [comment]
Upgrade your Node.js first，and execute the following commands one after another please

```bash
$ rm -Rf node_modules
$ rm package-lock.json
$ npm i -g yarn
$ yarn install
$ yarn dev
```

**Comment by suntsh** [comment]
> Upgrade your Node.js first，and execute the following commands one after another please
> 
> ```shell
> $ rm -Rf node_modules
> $ rm package-lock.json
> $ npm i -g yarn
> $ yarn install
> $ yarn dev
> ```

还真可以，yarn安装和npm安装有什么区别吗？ 我也没升级node.js

**Comment by jaysonwu991** [comment]
> > Upgrade your Node.js first，and execute the following commands one after another please
> > 
> > ```shell
> > $ rm -Rf node_modules
> > $ rm package-lock.json
> > $ npm i -g yarn
> > $ yarn install
> > $ yarn dev
> > ```
> 
> 还真可以，yarn安装和npm安装有什么区别吗？ 我也没升级node.js

Open official websites of yarn and pnpm, you will find more details. Just do IT.
